{{- if .Values.api.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "platform-app.name" . }}-api
  labels:
    {{- include "platform-app.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "api") | nindent 4 }}
    {{- with .Values.api.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "platform-app.componentSelectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "api") | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.api.serviceMonitor.path | quote }}
      interval: {{ .Values.api.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.api.serviceMonitor.scrapeTimeout }}
{{- end }}
