apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform-app.name" . }}-mariadb
  labels:
    {{- include "platform-app.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "mariadb") | nindent 4 }}
type: Opaque
stringData:
  database: {{ .Values.mariadb.database | quote }}
  username: {{ .Values.mariadb.username | quote }}
  password: {{ .Values.mariadb.password | quote }}
  root-password: {{ .Values.mariadb.rootPassword | quote }}
