apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-app.name" . }}-web
  labels:
    {{- include "platform-app.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "web") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
  selector:
    {{- include "platform-app.componentSelectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" "web") | nindent 4 }}
